# This is a GitHub Actions workflow file
name: Java Docker Build, Test, and Push

# This specifies when the workflow should be triggered
on:
  # Trigger the workflow on push events to the master branch
  push:
    branches:
      - master

# Define the jobs that will run as part of this workflow
jobs:
  # Define a job named 'build-test-and-push'
  build-test-and-push:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    # Steps define the sequence of tasks to be executed in the job
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use 'temurin' instead of 'adopt-openjdk'

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run JUnit tests with Maven
      - name: Run JUnit tests
        run: mvn test

      # Build the Docker image only if tests pass
      - name: Build Docker image
        if: success()  # This ensures the step runs only if all previous steps succeeded
        run: docker build -t shlomi00212/java_hello-world_app:1.0.${{ github.run_number }} .

      # Log in to Docker Hub only if the Docker build was successful
      - name: Log in to Docker Hub
        if: success()  # This ensures the step runs only if all previous steps succeeded
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub only if the login was successful
      - name: Push Docker image
        if: success()  # This ensures the step runs only if all previous steps succeeded
        run: docker push shlomi00212/java_hello-world_app:1.0.${{ github.run_number }}

      # Update Maven project version only if all previous steps were successful
      - name: Increment Maven Version
        if: success()  # This ensures the step runs only if all previous steps succeeded
        run: mvn versions:set -DnewVersion=1.0.${{ github.run_number }}
        env:
          MAVEN_OPTS: '-Xmx2g'
