name: Features Pipeline
#test
on:
  push:
    branches:
      - features

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven 3.9.2
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
          tar -xzf apache-maven-3.9.2-bin.tar.gz
          sudo mv apache-maven-3.9.2 /usr/local/apache-maven
          sudo rm -f /usr/bin/mvn
          sudo ln -s /usr/local/apache-maven/bin/mvn /usr/bin/mvn

      - name: Verify Maven version
        run: mvn -v

      - name: Build with Maven
        run: mvn clean install

      - name: Run JUnit tests
        run: mvn test

      - name: Merge changes to master
        if: success()
        run: |
          git fetch origin master  # Ensure we have the latest master branch
          git config user.name "${{ secrets.GIT_USERNAME }}"
          git config user.email "${{ secrets.EMAIL }}"
          git checkout master
          git merge features --no-ff --allow-unrelated-histories -m "Merge changes from features branch"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
