name: Feature to Master Pipeline

on:
  push:
    branches:
      - features

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven 3.9.2
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
          tar -xzf apache-maven-3.9.2-bin.tar.gz
          sudo mv apache-maven-3.9.2 /usr/local/apache-maven
          sudo rm -f /usr/bin/mvn
          sudo ln -s /usr/local/apache-maven/bin/mvn /usr/bin/mvn

      - name: Verify Maven version
        run: mvn -v

      - name: Build with Maven
        run: mvn clean install

      - name: Run JUnit tests
        run: mvn test

  
